# Experiment 07: LSTM with frame difference features
exp_name: exp07_lstm_frame_diff
exp_dir: src/exp07

# Data settings
data_dir: ./input/
predict_videos:
  - "2024-08-12_11-52-28_cam1_0.mp4"
  - "2024-08-12_12-27-01_cam1_0.mp4"

# Model architecture
model_type: lstm_improved
hidden_size: 256
num_layers: 3
dropout: 0.3
bidirectional: true
num_classes: 6

# Training settings
learning_rate: 0.001
weight_decay: 0.0001
batch_size: 32
epochs: 50
n_folds: 3
seed: 42


# Data processing
window_width: 3
num_kp: 17
min_keypoint_score: 0.6
min_bbox_ratio: 0.01
max_bbox_ratio: 0.3

# Output settings
output_dir: ./output/exp07/