# Configuration for Experiment 04: LSTM on bone features
experiment:
  name: "exp04_lstm_bone"
  description: "LSTM model using bone features for action recognition"
  model_type: "lstm"

# Model configuration
model:
  num_classes: 6
  hidden_size: 256
  num_layers: 2
  dropout: 0.5
  bidirectional: false
  
# Data configuration
data:
  data_dir: "input/data_10hz"
  pose_file: "pose_preds.csv"
  num_keypoints: 23
  window_size: 3
  features:
    - "bone_length"
    - "bone_angle"
  bones:
    - [0, 1]   # nose -> left_eye
    - [0, 2]   # nose -> right_eye
    - [1, 3]   # left_eye -> left_ear
    - [2, 4]   # right_eye -> right_ear
    - [5, 6]   # left_shoulder -> right_shoulder
    - [5, 7]   # left_shoulder -> left_elbow
    - [7, 9]   # left_elbow -> left_wrist
    - [6, 8]   # right_shoulder -> right_elbow
    - [8, 10]  # right_elbow -> right_wrist
    - [5, 11]  # left_shoulder -> left_hip
    - [6, 12]  # right_shoulder -> right_hip
    - [11, 12] # left_hip -> right_hip
    - [11, 13] # left_hip -> left_knee
    - [13, 15] # left_knee -> left_ankle
    - [12, 14] # right_hip -> right_knee
    - [14, 16] # right_knee -> right_ankle

# Preprocessing configuration
preprocessing:
  normalize_pose: true
  augment_side_switch: true
  
# Inference configuration
inference:
  batch_size: 32
  device: "cuda"
  checkpoint: "checkpoints/exp04/best.ckpt"
  
# Action names
action_names:
  - "lunge"
  - "fleche"
  - "counter"
  - "parry"
  - "prime"
  - "none"